name = "Now UI Free"
license = "N/A"
licenselink = ""
description = "A port of Creative Tim's Now UI theme for Hugo"
tags = ["blog", "bootstrap"]
features = ["blog"]
min_version = 0.51

[author]
	name = "Bruno Amaral"
	homepage = "http://brunoamaral.eu/"

